<?php
// Article - Print Design
?>

<h1>
    <div class="de-emphasized">Your message <u>IS</u> your business</div>
    <div class="emphasized"><em>Speak loudly</em></div>
</h1>

<p>Whether its a brochure, artwork for physical media, or a whole new brand identity that you need, Virtuosic Media has got you covered from concept to final printing.</p>

<p>We have experience delivering a wide range of print projects. Some of the things we do include:</p>
<br />
<ul>
    <li>Branding / Re-branding / Identity
        <ul>
            <li>Logo development</li>
            <li>Style guides</li>
            <li>Business cards / Letterhead / Envelopes</li>
        </ul>
    </li>
    <li>Mailers</li>
    <li>Product packaging</li>
    <li>CD and DVD / Blu-ray artwork and packaging</li>
    <li>Trifolds and Booklets / Magazines</li>
    <li>Posters</li>
    <li>Book Covers / Dust Jackets</li>
    <li>Newspaper / Magazine Ads</li>
</ul>

<p>If you have a marketing or physical media need, Virtuosic Media can help you cut through the noise, with fresh, vivid designs and well packaged products. We can even handle the printing of your artwork and physical media.</p>

<p>Here are a few samples of recent print work we've done.</p>

<div class="gallery clearfix">

    <!-- GFO Glossy -->
    <a class="iframe fade" href="images/source/GFOGlossy.pdf">
      <div class="item col-1 odd fade">
        <h2 class="portfolio fade">One-Sheet / Glossy</h2>
        <div class="image-wrapper">
          <img class="fade" src="images/thumbs/GFOGlossy-thumb.jpg" alt="View Full Screen">
        </div>
      </div>
    </a>

    <!-- Iron Circle DVD -->
    <a class="modal fade" href="images/source/IronCircleDVDCoverwrap.jpg">
      <div class="item col-2 even fade">
        <h2 class="portfolio fade">DVD Coverwrap / Logo Design</h2>
        <div class="image-wrapper">
          <img class="fade" src="images/thumbs/IronCircleDVDCoverwrap-thumb.jpg" alt="View Full Screen">
        </div>
      </div>
    </a>

    <!-- Convert of Hope Logo -->
    <a class="modal fade" href="images/source/ConcertofHopeLogo.jpg">
      <div class="item col-3 odd fade">
        <h2 class="portfolio fade">Logo Design</h2>
        <div class="image-wrapper">
          <img class="fade" src="images/thumbs/ConcertofHope-thumb.jpg" alt="View Full Screen">
        </div>
      </div>
    </a>

    <!-- Miracle CD -->
    <a class="modal fade" href="images/source/MiracleCD.jpg"><div class="item col-1 even fade"><h2 class="portfolio fade">CD Design</h2><div class="image-wrapper"><img class="fade" src="images/thumbs/MiracleCD-thumb.jpg" alt="View Full Screen"></div></div></a>

    <!-- Expressions CD -->
    <a class="modal fade" href="images/source/ExpressionsCD.jpg"><div class="item col-2 odd fade"><h2 class="portfolio fade">CD Design</h2><div class="image-wrapper"><img class="fade" src="images/thumbs/ExpressionsCD-thumb.jpg" alt="View Full Screen"></div></div></a>

    <!-- Determined CD -->
    <a class="modal fade" href="images/source/DeterminedCD.jpg"><div class="item col-3 even fade"><h2 class="portfolio fade">CD Design</h2><div class="image-wrapper"><img class="fade" src="images/thumbs/DeterminedCD-thumb.jpg" alt="View Full Screen"></div></div></a>

    <!-- Iron Circle Poster -->
    <a class="modal fade" href="images/source/IronCirclePoster.jpg"><div class="item col-1 odd fade"><h2 class="portfolio fade">Poster</h2><div class="image-wrapper"><img class="fade" src="images/thumbs/IronCirclePoster-thumb.jpg" alt="View Full Screen"></div></div></a>

    <!-- UNOH Teaser Poster -->
    <a class="modal fade" href="images/source/UNOHTeaserPoster.jpg"><div class="item col-2 odd fade"><h2 class="portfolio fade">Teaser Poster</h2><div class="image-wrapper"><img class="fade" src="images/thumbs/UNOHTeaserPoster-thumb.jpg" alt="View Full Screen"></div></div></a>

    <!-- WCOPF Logo -->
    <a class="modal fade" href="images/source/WCOPFLogo.jpg"><div class="item col-3 even fade"><h2 class="portfolio fade">Logo Design</h2><div class="image-wrapper"><img class="fade" src="images/thumbs/WCOPFLogo-thumb.jpg" alt="View Full Screen"></div></div></a>

    <!-- Trip Sports Info Book -->
    <a class="iframe fade" href="images/source/TripSportsInfoBook.pdf"><div class="item col-1 odd fade"><h2 class="portfolio fade">Booklet / Magazine</h2><div class="image-wrapper"><img class="fade" src="images/thumbs/TripSportsInfoBook-thumb.jpg" alt="View Full Screen"></div></div></a>

    <!-- Summerfest DVD -->
    <!-- <a class="modal fade" href="images/source/SummerFestDVD.jpg"><div class="item col-3 even fade"><h2 class="portfolio fade">DVD Artwork</h2><div class="image-wrapper"><img class="fade" src="images/thumbs/SummerFestDVD-thumb.jpg" alt="View Full Screen"></div></div></a> -->

    <!-- Phaals Trifold -->
    <!-- <a class="modal fade" href="images/source/PhaalsTrifold.jpg"><div class="item col-1 odd fade"><h2 class="portfolio fade">Trifold Brochure</h2><div class="image-wrapper"><img class="fade" src="images/thumbs/PhaalsTrifold-thumb.jpg" alt="View Full Screen"></div></div></a> -->

    <!-- GFO Trifold -->
    <!-- <a class="modal fade" href="images/source/GFOTrifold.jpg"><div class="item col-2 even fade"><h2 class="portfolio fade">Trifold Brochure</h2><div class="image-wrapper"><img class="fade" src="images/thumbs/GFOTrifold-thumb.jpg" alt="View Full Screen"></div></div></a> -->

    <!-- PEC Lima Bride -->
    <!-- <a class="modal fade" href="images/source/PECLimaBride.jpg"><div class="item col-3 odd fade"><h2 class="portfolio fade">Newspaper / Web Ads</h2><div class="image-wrapper"><img class="fade" src="images/thumbs/PECLimaBride-thumb.jpg" alt="View Full Screen"></div></div></a> -->

    <!-- Iron Circle Business Card -->
    <!-- <a class="modal fade" href="images/source/IronCircleBusinessCard.jpg"><div class="item col-2 even fade"><h2 class="portfolio fade">Business Card</h2><div class="image-wrapper"><img class="fade" src="images/thumbs/IronCircleBusinessCard-thumb.jpg" alt="View Full Screen"></div></div></a> -->

    <div class="clear-both"></div>
</div>

<div class="end-tag">
    <div class="de-emphasized">Cut through the noise</div>
    <div class="emphasized"><em>We can help</em></div>
</div>

  <a data-scroll-goto="0" class="return"><span class="highlight fade">Return to <em>top</em></span></a>
