<?php
// Article - Web Design
?>

<h1>
    <div class="de-emphasized">A great website makes you more productive, it shouldn't</div>
    <div class="emphasized"><em>slow you down</em></div>
</h1>

<p>As a self-employed creative or small business owner, <strong>time</strong> is your most valuable resource. At Virtuosic Media, we try to give you some of it back by building websites tailored to the way <strong>you</strong> work.</p>

<p>Here are a few samples of recent work.</p>

<div class="gallery clearfix">
	
	<!-- EYC --> 
    <a class="iframe fade" href="//www.eagleycondor.org">
      <div class="item col-1 even fade">
        <h2 class="portfolio fade">eagle Y condor</h2>
        <div class="image-wrapper">
          <img class="fade" src="images/thumbs/eyc-thumb.jpg" alt="Visit eagleycondor.org">
        </div>
      </div>
    </a>

    <!-- APME --> 
    <a class="iframe fade" href="//www.anthonypero.me">
      <div class="item col-2 even fade">
        <h2 class="portfolio fade">AnthonyPero.me</h2>
        <div class="image-wrapper">
          <img class="fade" src="images/thumbs/apme.jpg" alt="Visit the Portfolio of Anthony Pero">
        </div>
      </div>
    </a>

    <!-- PHAALS -->
    <a class="iframe fade" href="//www.phaals.org">
      <div class="item col-3 even fade">
        <h2 class="portfolio fade">The PHAALS Foundation</h2>
        <div class="image-wrapper">
          <img class="fade" src="images/phaals.jpg" alt="Visit the PHAALS Foundation">
        </div>
      </div>
    </a>

    <!-- AP Voiceovers -->
    <a class="iframe fade" href="//www.apvoiceovers.com">
      <div class="item col-1 even fade">
        <h2 class="portfolio fade">AP Voiceovers</h2>
        <div class="image-wrapper">
          <img class="fade" src="images/apvo-thumb.jpg" alt="Visit AP Voiceovers">
        </div>
      </div>
    </a>

    <!-- Up Systems -->
    <a class="iframe fade" href="//www.upsystems-inc.com">
      <div class="item col-2 even fade">
        <h2 class="portfolio fade">Up Systems, Inc.</h2>
        <div class="image-wrapper">
          <img class="fade" src="images/upsys.jpg" alt="Visit Up Systems, Inc">
        </div>
      </div>
    </a>

    <!-- Iron Circle -->
    <a class="iframe fade" href="//www.ironcirclemma.com">
      <div class="item col-3 odd fade">
        <h2 class="portfolio fade">Iron Circle MMA</h2>
        <div class="image-wrapper">
          <img class="fade" src="images/ironcircle.jpg" alt="Visit Iron Circle MMA">
        </div>
      </div>
    </a>

    <!-- LAH Consultations -->
    <!-- <a class="iframe fade" href="http://www.lahconsultations.com">
      <div class="item col-2 odd fade">
        <h2 class="portfolio fade">Living At Home Consultations</h2>
        <div class="image-wrapper">
          <img class="fade" src="images/lah.jpg" alt="Visit Living At Home Consultations">
        </div>
      </div>
    </a> -->

    <!-- WCOPF -->
    <!-- <a class="modal fade" href="images/source/WCOPF.jpg">
      <div class="item col-3 even fade">
        <h2 class="portfolio fade">West Central Ohio Paralysis Foundation</h2>
        <div class="image-wrapper">
          <img class="fade" src="images/wcopf.jpg" alt="View Fullscreen">
        </div>
      </div>
    </a> -->

    <div class="clear-both"></div>
</div>

<p>At <strong>Virtuosic Media</strong> we specialize in building content management systems that take the effort out of maintaining and updating your site. No more calls to a developer to add a new page, or update a photo. You can add and edit content as simply as using email, or Facebook.</p>

<p>We take the time to get to know you and the way you operate, then make suggestions for how your workflow can be improved by your website. Rather than eating up your time, your website can (and should) <strong>save you time</strong>.</p>

<p>Are you an author, musician, photographer or other creative? <a data-scroll-goto="5">We specialize</a> in building tools just for you! We even take care of hosting and maintenance.</p>

<p>Ready to know more? <a data-scroll-goto="7">Contact us</a> and find out how we can help you become more productive.</p>

<div class="end-tag">
    <div class="de-emphasized">Get more done in less time</div>
    <div class="emphasized"><em>We can help</em></div>
</div>

  <a data-scroll-goto="0" class="return"><span class="highlight fade">Return to <em>top</em></span></a>
