<?php
// FooterInfo
?>

<?php include '/var/www/html/virtuosic/inc/form.php'; ?>
<div class="bottom clearfix">
  <a data-scroll-goto="1"><div class="candy web fade">Web.</div></a>
  <a data-scroll-goto="3"><div class="candy print fade">Print.</div></a>
  <a data-scroll-goto="5"><div class="candy creative fade">Creatives.</div></a>
  <div class="copyright clear-both">Copyright &copy; <?php print date('Y'); ?> <a data-scroll-goto="0" class="pointer">Virtuosic Media</a>. All rights reserved.</div>
</div>  