<?php
    //Body Header -- Main Menu
?>

<header>
  <div class="img-inner"></div>
  <div class="wrapper">
    <h1><a href="#top" class="go-away">Virtuosic Media - Web and Media Development for Self-employed Creatives and Small Businesses</a></h1>
    <nav id="main-menu">
      <ul class="menu">
        <li><a class="fade" data-scroll-nav="1">Web Development</a></li>
        <li><a class="fade" data-scroll-nav="3">Print Design</a></li>
        <li><a class="fade" data-scroll-nav="5">For Creatives</a></li>
        <li><a class="fade" data-scroll-nav="7">Contact Us</a></li>
      </ul>
    </nav>
  </div>
</header>