<?php
// HTML Head Info
?>
 
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Web and media development for Self-Employed Creatives and Small Businesses - Virtuosic Media</title>
  <link rel="stylesheet" href="style.css">
  <link rel="stylesheet" href="inc/colorbox.css">
  <link href='//fonts.googleapis.com/css?family=Roboto:400,700|Roboto+Condensed:400,300,700|Roboto+Slab:700' rel='stylesheet' type='text/css'>
  <script src="js/jquery-1.11.0.min.js" type="text/javascript"></script>
  <script src="js/colorbox-master/jquery.colorbox.js"></script>
  <script src="js/scrollIt.js" type="text/javascript"></script>
  <!--[if lt IE 9]>
    <script src="js/html5shiv.min.js"></script>
  <![endif]-->
  <script>
      $(function(){
        $.scrollIt();
      });
  </script>
</head>
